### ISSUE TITLE
Job sharing

### ISSUE THREAD

**Issue by dracos** [popolo-project/popolo-spec#16]
If a parliament allows two people to jobshare the post of Member of Parliament for Avalon (a mooted proposal of at least one party here in the UK), and in general any Post that is shared between multiple people, how would this be modelled?

**Comment by jpmckinney** [comment]
The ORG ontology allows organizations to hold posts: http://www.w3.org/TR/vocab-org/ and it does that because the UK govt needed it to model its civil servants correctly. **Update:** The ORG ontology also does not prevent multiple people from holding a post.

In Popolo, I introduce a restriction to prevent that usage, in order to make the JSON and MongoDB serialization simpler, given that in the vast majority of cases, it's a single person holding a post: http://popoloproject.com/data.html#restrictions

We can lift that restriction and give Post a `person_ids` field which is an array of IDs, at the expense of making the data model more complex. Alternatively, we can keep the singular `person_id` and describe in which cases you might prefer to use `person_ids`.

How does that sound?

**Update:** Having potentially both `person_id` and `person_ids` means that you'd have to query both - an argument in favor of just picking one.

**Comment by jpmckinney** [comment]
Ok, taken care of by this proposal: https://github.com/opennorth/popolo-standard/wiki/2013-02-28-Rework-Membership-and-Post

Feel free to add comments on the proposal here or on the wiki page.

**Comment by jpmckinney** [comment]
Currently integrating that proposal into the spec. Continuing in #15
