### ISSUE TITLE
Naming of dates for easy updating when required.

### ISSUE THREAD

**Issue by evdb** [popolo-project/popolo-spec#18]
Summary: Each date should have an optional name that identifies the event it represents. This can subsequently be used to batch update dates - eg. changing imprecise future dates into precise ones when dates for events such as elections are confirmed.

This is something that might not belong in this spec, but it is something that in [Mzalendo](http://info.mzalendo.com/) we would have found very useful in the run up to the election.

All the MPs has positions with an end date of `2012` which is when the election was expected to occur, although the exact date was not known. The election was subsequently pushed to `2013` and then confirmed as being `4 Mar 2013`.

This required us to update the end dates of the MP positions. To do this we needed to do a query to find all the MP positions and then trust that the 2012 was in fact the anticipated end date.

Had we had these dates named we could have searched for them more easily, and the users of the data would have had more information about what the date represents. We'd have called it something like "Dissolution of 2007 Parliament".

Some way to search for existing date names would be required so that it is easy to find and reuse existing date names.

This need not be part of the spec, but it should be possible to add this sort of data to the records. PopIt almost certainly [would](https://github.com/mysociety/popit/issues/60#issuecomment-6756845).

**Comment by jpmckinney** [comment]
There are many ways to go here. Right now, no class has an array of dates, so we don't need names to disambiguate between different dates within a single document. To make sure I understand correctly, we want to be able to tag dates on different documents, so that we can find them easily later. The only use case given so far are dates on the parliamentary calendar, e.g. an election date or a term's end date, and this use case only affects end dates on Memberships for members of that parliament. If I understand, an important motivator for these tags is to be able to disambiguate between someone whose membership actually ended in 2012, and one whose membership was merely projected to end in 2012 but hasn't actually.

It's important to mention that in RDF, we can tag dates with user-defined datatypes, and avoid this question altogether.

Playing devil's advocate, what's wrong with the following proposal: Don't store future end dates. Is it really necessary to put on the Membership document the projected end date? Couldn't this information be provided in a less error-prone way, e.g. through a calendar? In this way, you would only set the end date once memberships had in fact ended.

**Update:** More importantly, you aren't actually storing the Membership's end date by doing what you propose. You're storing the date of some other thing - an end of a term or the date of an election. Popolo has no knowledge of Terms or Elections, but perhaps it should. Those dates should be on those objects, not on Memberships. Consider the cases where someone's membership ends before the projected date, e.g. resignation, death, etc. I'd prefer to add new classes to handle your use case; I anticipate a great deal of confusion if dates becomes objects that can represent all sorts of potential future outcomes.

**Comment by jpmckinney** [comment]
The more I think of it, the more I think you actually want an `Election` class (or a more general `Event` class), but since you don't have that class, you need to put its properties on every object that has something to do with that event.

**Comment by jpmckinney** [comment]
An `Event` class seems like the only way to avoid a logical extension of the original proposal in this issue, which can lead to:

``` json
# Membership
{
  "person_id": "1",
  "organization_id": "2",
  "end_date": [
    {
      "date": "2018",
      "note": "General election"
    },
    {
      "date": "2016",
      "note": "Court may sentence to incarceration, prompting resignation"
    },
    {
      "date": "2013-03-30",
      "note": "Heart attack"
    }
  ]
}
```

**Comment by jpmckinney** [comment]
@evdb see #22 for standards relating to an Event class

**Comment by evdb** [comment]
I think that using the events (#22) would address the motivations for adding names to dates. Closing.

**Comment by jpmckinney** [comment]
Issue summary: The recommendation would be to create an Event, which stores the date on which all memberships end (e.g. at prorogation, dissolution, etc.). Logic should be added to that event, such that once its date passes, all open-ended memberships to which it applies end on that date. This avoids a conflict in cases where a membership ends before the projected date.
