### ISSUE TITLE
Store reason for start and end of membership

### ISSUE THREAD

**Issue by evdb** [popolo-project/popolo-spec#20]
This is used in the TWFY codebase to describe the situation in which a representative starts and stops their tenure - see [instances in the codebase](https://github.com/search?q=entered_reason+repo%3Amysociety%2Ftheyworkforyou&type=Code&ref=searchresults) and a [list of example reasons](https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/member.php#L36)

They should be optional. The keys `start_reason` and `end_reason` could be used and the values be plain strings.

**Comment by jpmckinney** [comment]
This is a provenance question. The [PROV-O](http://www.w3.org/TR/prov-o/) vocabulary has classes and properties for describing change events in more detail. I'd want to investigate that existing standard before minting new terms. You can help by having a look yourself :)
- W3C Provenance working group
  - [Wiki](http://www.w3.org/2011/prov/wiki/Main_Page)
  - [Mailing list](http://lists.w3.org/Archives/Public/public-prov-wg/)
- [Dublin Core to PROV mapping](https://dvcs.w3.org/hg/prov/raw-file/ff940ee82d3d/dc-note/Overview.html)
  - [GitHub repository](https://github.com/dcmi/DC-PROV-Mapping)

**Comment by evdb** [comment]
Perhaps I'm missing something but there does not seem to be anything in the [PROV_O](http://www.w3.org/TR/prov-o/) spec that is applicable. They would link a [start](http://www.w3.org/TR/2012/CR-prov-o-20121211/#Start) to other classes in the ontology, rather than a simple textual description. The closest thing would be [`wasStartedBy`](http://www.w3.org/TR/2012/CR-prov-o-20121211/#wasStartedBy) property (and the related `wasEndedBy`).

**Comment by jpmckinney** [comment]
Actually, changeEvent is part of [ORG](http://www.w3.org/TR/vocab-org/#class--changeevent) but it's only for changes to organizations. It may however point to how to use PROV for similar events. Anyway, it's important to base standards on existing standards, otherwise it becomes a game of "my standard versus your standard." It's much better for the situation to be "it's your standard versus my standard _plus the dozen standards my standard is based on_" as is the case with Popolo currently.

**Comment by jpmckinney** [comment]
Also, PROV-O may not have the single property you want. For the JSON/MongoDB serialization, we can maybe simplify whatever it has to one property. But it's first important to understand how they do things and why they do it that way.

**Comment by jpmckinney** [comment]
As with #18, I am increasingly of the opinion that the only sane approach is to have an `Event` class. The Event class should have some type mechanism, whether as a property or by subclassing the event class, to account for all the event types in [TWFY](https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/member.php#L36).

The membership could reference an Event class with respect to its start and end dates. How does that sound? In this case, we can indeed inspire a lot from how ORG uses PROV-O. We can move the dates out of Membership entirely, but I think many use cases won't have anything on the Event besides the date, and so it's best to leave a mechanism for people who don't need full-fledged events (sort of like how Posts are optional).

It should have occurred to me earlier, but when we talk about making a property like a date into an object, that usually means making that property into a class with its own properties - thus `Event`. I think this is in line with what you're proposing. It just means more work, because there are about another 10 standards that deal with events that need to be reviewed.

**Comment by evdb** [comment]
Best implemented with events #22. Closing.
