### ISSUE TITLE
"tel:"-prefix and RFC 3966

### ISSUE THREAD

**Issue by akuckartz** [popolo-project/popolo-spec#62]
Currently http://popoloproject.com/specs/contact-detail.html states
"Telephone number values should be in RFC 3966 format, without the tel: prefix."

What is the reason for this non-conformance with RFC 3966 ? Not using "tel:" is also not consistent with the use of the "mailto:" prefix for mail adresses.

**Comment by jpmckinney** [comment]
The serialization section describes some differences between the plain JSON serialization and the JSON-LD serialization of Popolo: http://popoloproject.com/specs/#serialization

For telephone numbers, we're using `rdf:value` so there's no requirement for the value to be an IRI. Rather than introduce a difference between plain JSON and JSON-LD, I figured we'd omit the `tel:` in both serializations. Most users of Popolo do not expect a `tel:` prefix, and if we were to add it, then all current users will have to add code to remove those characters.

Plain JSON can omit the `mailto:` prefix (which is also what most users of Popolo expect), but JSON-LD must use `mailto:` because `schema:email` requires the value to be an IRI.

**Comment by akuckartz** [comment]
Thanks for the explanation. I am not necessarily happy with it but I understand the reason. Did you reasearch the use or non-use of `tel:' by other Linked Data communities?

**Comment by jpmckinney** [comment]
[FOAF uses tel:](http://xmlns.com/foaf/spec/#term_phone). We can recommend/require that the JSON-LD version have a `tel:` prefix, but no current user has taken advantage of the linked data serializations. For the current users, it's just an extra four characters that are confusing to their end-users, who just want to get a phone number. The transformation is very simple, so it's easy to turn JSON without tel: to JSON-LD with tel:.

**Comment by jpmckinney** [comment]
Unless there is a proposal to require `tel:` in the JSON-LD serialization, I will close this issue, as the question has been answered.

**Comment by akuckartz** [comment]
I will investigate this further for OpenGovLD. But that does not have a high priority. I will come back here when I have results.
