### ISSUE TITLE
Person 'summary' is missing

### ISSUE THREAD

**Issue by paultag** [popolo-project/popolo-spec#64]
http://popoloproject.com/specs/person.html

It's called `one-line biography` instead. I think that should be `summary` (under `The Person class should have properties for`)

**Comment by jpmckinney** [comment]
What change are you proposing? The use cases and requirements section is non-normative; it just lays out the needs that the spec should fulfill. In the case of Person, it's very bullet-point, but for [Membership](http://popoloproject.com/specs/membership.html) it's more descriptive.

In the Classes and properties section, the "term" column contains the human-readable version of the term. The "mapping" column gives the RDF term, which in most cases is identical to the JSON term (except it's snake_case instead of camelCase). The Serialization section notes any differences in the JSON term.

There should maybe be a column in the Classes and properties section for the JSON term. Would that resolve the issue?

**Comment by paultag** [comment]
Didn't know that was intentional. I was going to suggest `s/one-line biography/summary/g`, since that's the name the JSON schema uses. I was Control-f'ing for the term 'summary' (to figure out the difference between summary and biography) and didn't hit the description above.

If it's intentional, that's cool. Thought it might have been a mistake.

**Comment by jpmckinney** [comment]
Okay, I'll keep in mind adding a column for the JSON term as it would make searching easier.
