### ISSUE TITLE
Speech class

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#69]
Requested by @girogiro. To Review:
- [x] http://schema.org/CreativeWork
- [x] [Ontologia Camera dei Deputati RDF Schema 1.2](http://dati.camera.it/ocd/reference_document/)
- [x] [LIPARM](http://www.liparm.ac.uk/?page_id=103): proceedings objects
- [x] AkomaNtoso
  - http://examples.akomantoso.org/categorical.html#speechAttsAG
  - http://examples.akomantoso.org/categorical.html#ANcontainersEG
  - http://sayit.mysociety.org/about/developers#an
  - https://github.com/mysociety/sayit/blob/master/speeches/importers/import_akomantoso.py#L27
- [x] Canada Hansard
- [x] http://oda.ft.dk/Home/OdaModel
- [x] SayIt
  - http://shakespeare.sayit.mysociety.org/api/v0.1/section/?format=json
  - http://shakespeare.sayit.mysociety.org/api/v0.1/speech/?format=json
  - https://github.com/mysociety/sayit/blob/master/speeches/models.py
- [x] [Talk of Europe](http://linkedpolitics.ops.few.vu.nl/home) has no vocabulary documentation, but it's possible to see its term names at [[1]](http://linkedpolitics.ops.few.vu.nl/api/export_graph_schema?graph=English_texts_with_paragraphs&mimetype=text%2Fplain&format=turtle), [[2]](http://linkedpolitics.ops.few.vu.nl/api/export_graph_schema?graph=file%3A%2F%2F%2Fhome%2Flinkedpolitics%2FTriples_XMLtoRDF%2FDebate_structure.ttl&mimetype=text%2Fplain&format=turtle), [[3]](http://linkedpolitics.ops.few.vu.nl/api/export_graph_schema?graph=MembersOfParliament_background&mimetype=text%2Fplain&format=turtle). It adds no new terms of interest.

[DebatesCore](http://www.vie-publique.fr/forums/debatescore/debatescore-norme.html) came out since this issue was closed, but it's mostly Dublin Core.

**Comment by akuckartz** [comment]
Regarding Akoma Ntoso (including some links) see also https://github.com/OpenGovLD/specs/issues/55

**Comment by jpmckinney** [comment]
Thanks - I'm quite familiar with AN; I reviewed it for the voting specs, and I've used it extensively in a recent project that uses [SayIt](http://sayit.poplus.org/), which imports AN XML.

**Comment by girogiro** [comment]
Request for comments on the Speech class proposal. Based on the SayIt model, pruned and slightly adapted to government debates.

## Properties

| Term | Mapping | Definition |
| --- | --- | --- |
| organization | org:organization | The organization where the speech took place |
| legislative session | opengov:legislativeSession | The legislative session in which the speech took place [[1]](#foot1) |
| speaker | schema:creator | The person who gave the speech |
| post | opengov:post | The post held by the speaker [[2]](#foot2) |
| start date | schema:startDate | The date and time at which the speech begins |
| end date | schema:endDate | The date and time at which the speech ends |
| number | schema:position | The number of the speech within a debate [[3]](#foot3) |
| type | rdf:type | A type of speech [[4]](#foot4) |
| text | schema:text | Text of the speech |

Notes:

<a name="foot1"></a>[1] The term _legislative session_ has been chosen for consistency with Motion class. A more general term _event_ might be used instead in both cases assuming that sessions will be modelled by a new Event class.

<a name="foot2"></a>[2] I am not sure about the _post_ property. The need is to model speeches of other people then members of the legislative body and to have additional information like "president", "secretary-general of the United Nations" or "an ordinary citizen" beside the speaker name. Other alternatives for the property could be like _on behalf of_ or _role_. Nevertheless, _post_ is most descriptive IMHO for the case. On the other hand, I think that many implementation don't use the Post class because they focus on the people more than on structure of organizations.

<a name="foot3"></a>[3] Useful to chronologically sort the speeches in case that date properties are empty. The term _number_ is used instead of _num_ in SayIt and AkomaNtoso to avoid abbreviations. Term _position_ might be also used instead of _number_.

<a name="foot4"></a>[4] E.g. `speech`, `question`, `answer`, `scene`, `narrative`, `summary`, `procedural`, `point of order`. Implementations may use values from outside the list.

The class contains also common meta-information properties _id_, _links_, _sources_, etc.

## Other thoughts

Do we need a container class to structure speeches into sections within a debate?

Why legislative session mapping is `opengov:legislativeSession` in Motion class while `schema:superEvent` in VoteEvent?

**Comment by jpmckinney** [comment]
Thanks, @girogiro !

Having used SayIt, I think it's useful to have sections. We can use `schema:isPartOf` to refer to the section.

Motion uses `opengov:legislativeSession` because there was no alternative, so we had to mint a new property. VoteEvent can use `schema:superEvent` because VoteEvent is a subclass of `schema:Event`.

Re: session versus event: I think we would want both. Event is useful for organizing speeches into sittings (usually one per day), whereas legislative sessions are longer.

In my use of SayIt, I noticed that some Nova Scotia speeches had titles (e.g. Question 1, Resolution 123, etc.). These are artifacts of the original transcripts, but worth retaining. We can maybe use `schema:name`.

I'm also not sure about putting `post` on the speech. In my use case, I just pull up the relevant post that the person speaking is linked to through their memberships. However, once we start scraping committee evidence, we'll have witnesses who aren't tracked like members of the legislature. We could create memberships and organizations for them, but it seems simpler / less error-prone to just have a description of their affiliation on the speech itself... We can maybe omit this property to start and wait until we have a clearer idea on what's needed.

**Comment by jpmckinney** [comment]
**Update:** Oops, was confused.

**Comment by girogiro** [comment]
Some experience from my use case - I am scraping parliamentary debates of Slovak parliament from the last 20 years.

Sometimes an invited speaker is giving a speech in a parliamentary session, e.g. a ministry, chairman of Constitutional court, president of a medical insurrance provider, Slovak national bank representative or even an ice hockey champion. There is no more information than short name of the person and his/her affiliation (e.g. "M. Šatan, captain of Slovak ice hockey team"). I create a new person entity in that case (to group all speeches of the person) and I store the affiliation information into the speech entity. I changed the property name to `label` rather than `post` to avoid confusion with the Post class. `affiliation` may be an even better name for that property. Btw, I do not use Post class for the Slovak parliament.

I plan to export the debates to SayIt after they are scraped. I intended to group them into sittings by date on export without a need for a section property. But it's true that explicit section is a more flexible approach. In older Slovak debates there is only a long document with sitting transcript, so I assign the date when the sitting started to all individual speeches. But in more recent debates there is start time and end time of each individual speech and sometimes a sitting lasts over midnight so the speech actually belongs to a sitting with different date that the speech itself took place.

Are properties for legislative session and sitting enough for parliamentary debates or a Section class is needed to allow sections within a sitting and subsections within a section? That's a question.

More people is working on scraping of other central European parliaments into Popolo model within our Visegrad+ project now and we are starting to move to the debates. So we need some common standard quite soon. This is the reason why I started it and trying to prove it on a real use case. If you add a draft spec, I will be more than happy.

We are going to scrape also western Balkan parliaments until the end of the year within the project, so there should be up to 10 European parliaments' debates exported to SayIt quite soon.

**Comment by jpmckinney** [comment]
Re: sections, in Nova Scotia, there are some top-level sections that are always on the agenda, e.g. petitions. Within those sections, there can be subsections, e.g. discussion of a specific bill. The elected officials call up different points on the agenda as they go through it. So, if you want to read the debate about a specific bill, we can link to the subsection for that debate. I don't think Sections are always necessary (or even possible), but they're useful when available.

**Comment by jpmckinney** [comment]
@girogiro The draft Speech class is ready http://www.popoloproject.com/specs/speech.html Organization and legislative session will go on the Event class. I omitted end date since that data is rarely available, but if you have some examples of real data, it can be added. I've opened a new issue for feedback #74

**Comment by girogiro** [comment]
Thank you! Going to implement and test it.
