### ISSUE TITLE
Links to video or audio

### ISSUE THREAD

**Issue by akuckartz** [popolo-project/popolo-spec#75]
This was suggested in https://github.com/opennorth/popolo-spec/issues/74#issuecomment-64418765 I suggest to continue the discussion here (separate from the other topics in that issue).

Some questions:
- links to files and/or streams ? 
- what about video files or streams in different formats ?
- video/audio objects which contain further information such as mime type or meta information?

Some ontologies have been created for mime types etc. Some of that work could be used here.

**Comment by jpmckinney** [comment]
Schema.org uses `MediaObject`s as the range of `audio` and `video`: http://schema.org/AudioObject http://schema.org/VideoObject

I think in most cases, people will just want to link directly to the audio/video however. For Popolo, the JSON Schema just requires that it's a URI, so it can either be a URI to RDF or to the actual media file.

**Comment by akuckartz** [comment]
If http://schema.org/video is used then the property should only link to VideoObject objects - at least in the JSON-LD version of Popolo.

**Comment by jpmckinney** [comment]
Indeed

**Comment by girogiro** [comment]
So let's add the `video` property to the Speech class.

**Comment by jpmckinney** [comment]
I've added a note about the JSON-LD range for `audio` and `video` to the [Serialization](http://www.popoloproject.com/specs/#serialization) section.

The schema terms were the only [existing terms](http://www.popoloproject.com/appendices/terms.html#Speech) that were found for relating a speech/work to its audio/video. The two possibilities were linking directly to media files and linking to metadata about media files. Schema.org links to metadata, so that's what we have in JSON-LD.

Unless I misunderstood the issue, I think this closes the issue.
