### ISSUE TITLE
http://popoloproject.com/schemas/person.json no longer exists

### ISSUE THREAD

**Issue by tmtmtmtm** [popolo-project/popolo-spec#85]
I now need to explicitly use http://www.popoloproject.com/schemas/person.json instead.

I can change my validator scripts to use the www version easily enough, but reporting in case this wasn't deliberate.

**Comment by jpmckinney** [comment]
I'll set up a small proxy to 301 redirect the bare domain to `www.`. Unfortunately my DNS provider's 301 redirect service doesn't maintain URL paths. However, it's not a bad idea to change the URLs in your scripts.

I had switched to `www.` because my DNS provider doesn't support ALIAS or ANAME records. My reason for switching is from my experience with Heroku https://devcenter.heroku.com/articles/apex-domains

**Comment by jpmckinney** [comment]
It works again!

if your scripts don't follow redirects, you'll still need to update URLs.

**Comment by tmtmtmtm** [comment]
Great, thanks!
